dataops_mlops:
  target: local
  outputs:
    local:
      type: duckdb
      path: "/Users/batuhansaylam/Documents/Codex/2026-07-04/a/outputs/yahooquery_lakehouse_revamp/database/duckdb/dataops_mlops.duckdb"
      threads: 4

      extensions:
        - httpfs
        - delta

      secrets:
        - type: s3
          provider: config
          key_id: admin
          secret: admin1234
          region: us-east-1
          endpoint: 127.0.0.1:9000
          use_ssl: false
          url_style: path
          scope: "s3://delta-lake-bucket"

    devcontainer:
      type: duckdb
      path: "/opt/duckdb/dataops_mlops.duckdb"
      threads: 4

      extensions:
        - httpfs
        - delta

      secrets:
        - type: s3
          provider: config
          key_id: admin
          secret: admin1234
          region: us-east-1
          endpoint: host.docker.internal:9000
          use_ssl: false
          url_style: path
          scope: "s3://delta-lake-bucket"
