from __future__ import annotations

from .writers_class import *  # noqa: F403
from .writers_class import RuntimeBootstrapWriter

runtime_bootstrap_writer = RuntimeBootstrapWriter()
runtime_dependencies = runtime_bootstrap_writer.runtime_dependencies
write_requirements = runtime_bootstrap_writer.write_requirements
write_dbt_runtime_project = runtime_bootstrap_writer.write_dbt_runtime_project
write_feature_repo_runtime = runtime_bootstrap_writer.write_feature_repo_runtime
write_dagster_home = runtime_bootstrap_writer.write_dagster_home
prepare_duckdb_runtime = runtime_bootstrap_writer.prepare_duckdb_runtime
