from __future__ import annotations

from .pipeline_class import *  # noqa: F403
from .pipeline_class import StockClosePipelineFactory

stock_close_pipeline_factory = StockClosePipelineFactory()
_feature_engineering_context_nodes = stock_close_pipeline_factory._feature_engineering_context_nodes
_close_model_dataset_nodes = stock_close_pipeline_factory._close_model_dataset_nodes
_indicator_feature_nodes = stock_close_pipeline_factory._indicator_feature_nodes
_load_indicator_feature_nodes = stock_close_pipeline_factory._load_indicator_feature_nodes
_conventional_gap_trading_nodes = stock_close_pipeline_factory._conventional_gap_trading_nodes
_machine_learning_nodes = stock_close_pipeline_factory._machine_learning_nodes
_root_model_performance_inputs = stock_close_pipeline_factory._root_model_performance_inputs
create_feature_engineering_pipeline = stock_close_pipeline_factory.create_feature_engineering_pipeline
create_conventional_gap_trading_pipeline = stock_close_pipeline_factory.create_conventional_gap_trading_pipeline
create_machine_learning_pipeline = stock_close_pipeline_factory.create_machine_learning_pipeline
create_mlflow_root_performance_pipeline = stock_close_pipeline_factory.create_mlflow_root_performance_pipeline
create_pipeline = stock_close_pipeline_factory.create_pipeline
