from __future__ import annotations

from .workflow_class import *  # noqa: F403
from .workflow_class import PecnetTrainingWorkflow

pecnet_training_workflow = PecnetTrainingWorkflow()
train_pecnet_models_from_split = pecnet_training_workflow.train_pecnet_models_from_split
_concat_or_empty = pecnet_training_workflow._concat_or_empty
_ticker_jobs = pecnet_training_workflow._ticker_jobs
_run_ticker_job = pecnet_training_workflow._run_ticker_job
_run_ticker_job_in_child_process = pecnet_training_workflow._run_ticker_job_in_child_process
_append_ticker_result = pecnet_training_workflow._append_ticker_result
_publish_deferred_preprocessed_inputs = pecnet_training_workflow._publish_deferred_preprocessed_inputs
_publish_pecnet_preprocessed_frame = pecnet_training_workflow._publish_pecnet_preprocessed_frame
_pecnet_worker_count = pecnet_training_workflow._pecnet_worker_count
_pecnet_worker_torch_threads = pecnet_training_workflow._pecnet_worker_torch_threads
_resolve_worker_count = pecnet_training_workflow._resolve_worker_count
