from __future__ import annotations

from .data_class import MLForecastDataPreparer

mlforecast_data_preparer = MLForecastDataPreparer()
to_mlforecast_dataset = mlforecast_data_preparer.to_dataset
_business_day_grid = MLForecastDataPreparer._business_day_grid
fill_mlforecast_business_day_gaps = mlforecast_data_preparer.fill_business_day_gaps
to_mlforecast_frame = mlforecast_data_preparer.to_frame
make_train_test_split = mlforecast_data_preparer.make_train_test_split
