from __future__ import annotations

from .models_class import MLForecastModelFactory

mlforecast_model_factory = MLForecastModelFactory()
_worker_count = MLForecastModelFactory._worker_count
_max_estimators = MLForecastModelFactory._max_estimators
_estimator_verbose = MLForecastModelFactory._estimator_verbose
ridge_config = MLForecastModelFactory.ridge_config
random_forest_config = MLForecastModelFactory.random_forest_config
lightgbm_config = MLForecastModelFactory.lightgbm_config
xgboost_config = MLForecastModelFactory.xgboost_config
catboost_config = MLForecastModelFactory.catboost_config
init_config = MLForecastModelFactory.init_config
fit_config = MLForecastModelFactory.fit_config
build_auto_models = mlforecast_model_factory.build_auto_models
build_custom_auto_models = mlforecast_model_factory.build_custom_auto_models
