from __future__ import annotations

from .spec_class import MLForecastSpecBuilder

mlforecast_spec_builder = MLForecastSpecBuilder()
build_auto_mlforecast = mlforecast_spec_builder.build_auto_mlforecast
build_auto_mlforecast_spec = mlforecast_spec_builder.build_spec
_trial_logger = MLForecastSpecBuilder._trial_logger
