from __future__ import annotations

from .plots_class import *  # noqa: F403
from .plots_class import ForecastPlotter

forecast_plotter = ForecastPlotter()
forecast_model_columns = forecast_plotter.forecast_model_columns
_safe_name = forecast_plotter._safe_name
log_forecast_plots = forecast_plotter.log_forecast_plots
_forecast_train_test_figure = forecast_plotter._forecast_train_test_figure
_normalized_forecast_frame = forecast_plotter._normalized_forecast_frame
_ordered_symbols = forecast_plotter._ordered_symbols
_plot_prediction_intervals = forecast_plotter._plot_prediction_intervals
_log_directional_confusion_matrix = forecast_plotter._log_directional_confusion_matrix
_local_metrics_artifact_file = forecast_plotter._local_metrics_artifact_file
