from __future__ import annotations

from .definitions_class import *  # noqa: F403
from .definitions_class import FeatureStoreDefinitions

feature_store_definitions = FeatureStoreDefinitions()
_apply_model_feature_definitions = feature_store_definitions._apply_model_feature_definitions
_apply_pecnet_preprocessed_definition_and_push = feature_store_definitions._apply_pecnet_preprocessed_definition_and_push
_apply_feast_definitions_and_push = feature_store_definitions._apply_feast_definitions_and_push
_apply_close_model_dataset_definition = feature_store_definitions._apply_close_model_dataset_definition
_apply_close_model_dataset_definition_and_push = feature_store_definitions._apply_close_model_dataset_definition_and_push
_apply_with_registry_repair = feature_store_definitions._apply_with_registry_repair
