from __future__ import annotations

from .loaders_model_class import *  # noqa: F403
from .loaders_model_class import ModelFeatureLoader

model_feature_loader = ModelFeatureLoader()
_empty_model_training_dataset_frame = model_feature_loader._empty_model_training_dataset_frame
_read_tier2_online_entity_rows = model_feature_loader._read_tier2_online_entity_rows
_tier2_online_entity_batches = model_feature_loader._tier2_online_entity_batches
load_stock_model_training_dataset_from_feast_online = model_feature_loader.load_stock_model_training_dataset_from_feast_online
load_stock_tier1_model_dataset_from_feast_online = model_feature_loader.load_stock_tier1_model_dataset_from_feast_online
load_stock_tier2_model_dataset_from_feast_online = model_feature_loader.load_stock_tier2_model_dataset_from_feast_online
load_stock_tier3_model_dataset_from_feast_online = model_feature_loader.load_stock_tier3_model_dataset_from_feast_online
get_online_model_features = model_feature_loader.get_online_model_features
