from __future__ import annotations

from .loaders_close_class import *  # noqa: F403
from .loaders_close_class import CloseModelFeatureLoader

close_model_feature_loader = CloseModelFeatureLoader()
_read_close_model_entity_rows = close_model_feature_loader._read_close_model_entity_rows
_read_close_model_online_entity_rows = close_model_feature_loader._read_close_model_online_entity_rows
load_stock_close_model_dataset_from_feast = close_model_feature_loader.load_stock_close_model_dataset_from_feast
_empty_close_model_dataset_frame = close_model_feature_loader._empty_close_model_dataset_frame
_online_entity_batches = close_model_feature_loader._online_entity_batches
load_stock_close_model_dataset_from_feast_online = close_model_feature_loader.load_stock_close_model_dataset_from_feast_online
load_stock_close_model_dataset_from_redis = close_model_feature_loader.load_stock_close_model_dataset_from_redis
load_stock_close_model_dataset_from_timescale = close_model_feature_loader.load_stock_close_model_dataset_from_timescale
