from __future__ import annotations

from .publishers_class import *  # noqa: F403
from .publishers_class import FeatureStorePublisher

feature_store_publisher = FeatureStorePublisher()
publish_close_model_dataset = feature_store_publisher.publish_close_model_dataset
publish_model_features = feature_store_publisher.publish_model_features
publish_conventional_gap_trading = feature_store_publisher.publish_conventional_gap_trading
publish_pecnet_preprocessed_training_data = feature_store_publisher.publish_pecnet_preprocessed_training_data
