from __future__ import annotations

from .schemas_class import *  # noqa: F403
from .schemas_class import TimescaleSchemaManager

timescale_schema_manager = TimescaleSchemaManager()
_postgres_type_for_feature_column = timescale_schema_manager._postgres_type_for_feature_column
_create_timescale_feature_table = timescale_schema_manager._create_timescale_feature_table
_create_timescale_close_model_dataset_table = timescale_schema_manager._create_timescale_close_model_dataset_table
_postgres_type_for_conventional_gap_column = timescale_schema_manager._postgres_type_for_conventional_gap_column
_create_timescale_conventional_gap_trading_table = timescale_schema_manager._create_timescale_conventional_gap_trading_table
_create_timescale_pecnet_preprocessed_table = timescale_schema_manager._create_timescale_pecnet_preprocessed_table
