from __future__ import annotations

from .writers_class import *  # noqa: F403
from .writers_class import TimescaleFeatureWriter

timescale_feature_writer = TimescaleFeatureWriter()
_write_model_features_to_timescale = timescale_feature_writer._write_model_features_to_timescale
_write_close_model_dataset_to_timescale = timescale_feature_writer._write_close_model_dataset_to_timescale
_write_conventional_gap_trading_to_timescale = timescale_feature_writer._write_conventional_gap_trading_to_timescale
_write_pecnet_preprocessed_to_timescale = timescale_feature_writer._write_pecnet_preprocessed_to_timescale
